"""marketplace, authors, opinion posts

Revision ID: 12842f7df238
Revises: d2561a68b9bc
Create Date: 2026-09-07 22:43:52.812554
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '12842f7df238'
down_revision: str | None = 'd2561a68b9bc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=160), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authors')),
    sa.UniqueConstraint('slug', name=op.f('uq_authors_slug'))
    )
    op.create_table('marketplace_apps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('tagline', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('repo_url', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('pricing', sa.String(length=20), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=120), nullable=False),
    sa.Column('author_url', sa.Text(), nullable=True),
    sa.Column('submitter_email', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplace_apps')),
    sa.UniqueConstraint('slug', name=op.f('uq_marketplace_apps_slug'))
    )
    op.create_index('ix_marketplace_status', 'marketplace_apps', ['status', 'category'], unique=False)
    op.create_table('opinion_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('dek', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('hero_image_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name=op.f('fk_opinion_posts_author_id_authors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opinion_posts')),
    sa.UniqueConstraint('slug', name=op.f('uq_opinion_posts_slug'))
    )
    op.create_index('ix_opinion_published', 'opinion_posts', ['status', 'published_at'], unique=False)
    # ### end Alembic commands ###
    # keep the expression FTS/trgm indexes from the initial migration (autogen can't model them)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_opinion_published', table_name='opinion_posts')
    op.drop_table('opinion_posts')
    op.drop_index('ix_marketplace_status', table_name='marketplace_apps')
    op.drop_table('marketplace_apps')
    op.drop_table('authors')
    # ### end Alembic commands ###
