"""newsletter subscribers

Revision ID: 3bc4a313a70e
Revises: 12842f7df238
Create Date: 2026-09-07 23:48:37.583229
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '3bc4a313a70e'
down_revision: str | None = '12842f7df238'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('locale', sa.String(length=4), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter_subscribers')),
    sa.UniqueConstraint('email', name=op.f('uq_newsletter_subscribers_email'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ### || ' '::text) || COALESCE(summary, ''::text))")], unique=False, postgresql_using='gin') || ' '::text) || COALESCE(clean_summary, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_table('newsletter_subscribers')
    # ### end Alembic commands ###
