"""article + event body_text

Revision ID: c3b0a209a128
Revises: 3bc4a313a70e
Create Date: 2026-09-08 08:55:53.482189
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c3b0a209a128'
down_revision: str | None = '3bc4a313a70e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('body_text', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('body_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('events', 'body_text')
    op.drop_column('articles', 'body_text')
