"""initial schema

Revision ID: d2561a68b9bc
Revises: 
Create Date: 2026-09-07 18:00:55.848669
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'd2561a68b9bc'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('tier', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['entities.id'], name=op.f('fk_entities_parent_id_entities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
    sa.UniqueConstraint('slug', name=op.f('uq_entities_slug'))
    )
    op.create_index('ix_entities_type', 'entities', ['type'], unique=False)
    op.create_table('ingest_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job', sa.String(length=60), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('items_seen', sa.Integer(), nullable=False),
    sa.Column('items_written', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_runs'))
    )
    op.create_table('topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('keywords', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('slug', name=op.f('uq_topics_slug'))
    )
    op.create_table('videos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('youtube_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('playlist', sa.String(length=60), nullable=True),
    sa.Column('topics', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_videos')),
    sa.UniqueConstraint('youtube_id', name=op.f('uq_videos_youtube_id'))
    )
    op.create_index('ix_videos_published', 'videos', ['published_at'], unique=False)
    op.create_table('entity_relations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_entity_id', sa.Uuid(), nullable=False),
    sa.Column('to_entity_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.String(length=30), nullable=False),
    sa.Column('since', sa.Date(), nullable=True),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_entity_id'], ['entities.id'], name=op.f('fk_entity_relations_from_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_entity_id'], ['entities.id'], name=op.f('fk_entity_relations_to_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_relations')),
    sa.UniqueConstraint('from_entity_id', 'to_entity_id', 'relation', name='entity_relations_edge')
    )
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('primary_entity_id', sa.Uuid(), nullable=True),
    sa.Column('impact', sa.String(length=10), nullable=False),
    sa.Column('importance', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_top_signal', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('merged_into_id', sa.Uuid(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['events.id'], name=op.f('fk_events_merged_into_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_entity_id'], ['entities.id'], name=op.f('fk_events_primary_entity_id_entities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('slug', name=op.f('uq_events_slug'))
    )
    op.create_index('ix_events_category_importance', 'events', ['category', 'importance'], unique=False)
    op.create_index('ix_events_last_activity', 'events', ['last_activity_at'], unique=False)
    op.create_index('ix_events_top_signal', 'events', ['is_top_signal', 'importance'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('homepage_url', sa.Text(), nullable=False),
    sa.Column('feed_url', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('trust_weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('poll_interval_sec', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_sources_entity_id_entities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('slug', name=op.f('uq_sources_slug'))
    )
    op.create_table('topic_trend_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('window', sa.String(length=8), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('weighted_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('delta_pct', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_topic_trend_snapshots_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_trend_snapshots'))
    )
    op.create_index('ix_trend_lookup', 'topic_trend_snapshots', ['window', 'captured_at', 'rank'], unique=False)
    op.create_table('video_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_video_links_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_links')),
    sa.UniqueConstraint('video_id', 'target_type', 'target_id', name='video_link_edge')
    )
    op.create_table('articles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('raw_summary', sa.Text(), nullable=True),
    sa.Column('clean_summary', sa.Text(), nullable=True),
    sa.Column('body_excerpt', sa.Text(), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('dedup_simhash', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_articles_event_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_articles_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles')),
    sa.UniqueConstraint('source_id', 'external_id', name='article_source_external')
    )
    op.create_index('ix_articles_content_hash', 'articles', ['content_hash'], unique=False)
    op.create_index('ix_articles_published', 'articles', ['published_at'], unique=False)
    op.execute(
        "CREATE INDEX ix_articles_title_trgm ON articles USING gin (title gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_articles_fts ON articles USING gin "
        "(to_tsvector('english', coalesce(title,'') || ' ' || coalesce(clean_summary,'')))"
    )
    op.execute(
        "CREATE INDEX ix_events_fts ON events USING gin "
        "(to_tsvector('english', coalesce(title,'') || ' ' || coalesce(summary,'')))"
    )
    op.execute(
        "CREATE INDEX ix_entities_name_trgm ON entities USING gin (name gin_trgm_ops)"
    )
    op.create_table('event_entities',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_event_entities_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_entities_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'entity_id', name=op.f('pk_event_entities'))
    )
    op.create_table('event_topics',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_topics_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_event_topics_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'topic_id', name=op.f('pk_event_topics'))
    )
    op.create_table('importance_factors',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('source_reliability', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('independent_sources', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('entity_impact', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('novelty', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('market_impact', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('velocity', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('total', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_importance_factors_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_importance_factors'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('importance_factors')
    op.drop_table('event_topics')
    op.drop_table('event_entities')
    op.execute("DROP INDEX IF EXISTS ix_entities_name_trgm")
    op.execute("DROP INDEX IF EXISTS ix_events_fts")
    op.execute("DROP INDEX IF EXISTS ix_articles_fts")
    op.execute("DROP INDEX IF EXISTS ix_articles_title_trgm")
    op.drop_index('ix_articles_published', table_name='articles')
    op.drop_index('ix_articles_content_hash', table_name='articles')
    op.drop_table('articles')
    op.drop_table('video_links')
    op.drop_index('ix_trend_lookup', table_name='topic_trend_snapshots')
    op.drop_table('topic_trend_snapshots')
    op.drop_table('sources')
    op.drop_index('ix_events_top_signal', table_name='events')
    op.drop_index('ix_events_last_activity', table_name='events')
    op.drop_index('ix_events_category_importance', table_name='events')
    op.drop_table('events')
    op.drop_table('entity_relations')
    op.drop_index('ix_videos_published', table_name='videos')
    op.drop_table('videos')
    op.drop_table('topics')
    op.drop_table('ingest_runs')
    op.drop_index('ix_entities_type', table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
